using System.Collections.Specialized;

namespace HSPI_IRobot.Resources;

public class RobotErrorCodes {
	public static OrderedDictionary GetErrorCodesVersion4() {
		return new OrderedDictionary {
			{1, "Left wheel dropped"},
			{2, "Brushes cannot spin"},
			{3, "Right wheel dropped"},
			{4, "Left wheel jammed"},
			{5, "Right wheel jammed"},
			{6, "Drop off detected - check cliff sensors"},
			{7, "Left wheel drop sensor issue"},
			{8, "Vacuum has poor suction"},
			{9, "Bumper jammed or dislodged"},
			{10, "Right wheel drop sensor issue"},
			{11, "Vacuum motor cannot activate"},
			{12, "Drop off detected - check cliff sensors"},
			{13, "Uneven ground"},
			{14, "Bin not detected"},
			{15, "Internal board error - reboot robot"},
			{16, "Bumped upon start - bumper possibly dislodged"},
			{17, "Navigation problem"},
			{18, "Docking problem"},
			{19, "Undocking problem"},
			{20, "Internal communication error - reboot robot"},
			{21, "Internal mobility board error - reboot robot"},
			{22, "Stuck"},
			{23, "Battery authentication error"},
			{24, "Uneven ground"},
			{25, "Internal board error - reboot robot"},
			{26, "Vacuum stall - check filter"},
			{27, "Vacuum motor overheat - check filter"},
			{28, "Error 28"},
			{29, "Software upgrade error"},
			{30, "Vacuum failed to start"},
			{31, "Internal board error - reboot robot"},
			{32, "Smart map version mismatch - reboot robot"},
			{33, "Path blocked"},
			{34, "Internal comms error - reboot robot"},
			{35, "Incompatible mopping pad"},
			{36, "Cannot empty bin - check bin full sensor"},
			{37, "Tank is empty"},
			{38, "Internal power comms issue - reboot robot"},
			{39, "Internal power comms issue - reboot robot"},
			{40, "Stuck in virtual wall beam"},
			{41, "Mission timed out"},
			{42, "Failed to re-localize - move back to home base"},
			{43, "Started too close to home base"},
			{44, "Pump motor failed to start"},
			{45, "Lid open"},
			{46, "Low battery"},
			{47, "Invalid robot calibration - reboot robot"},
			{48, "Invalid robot calibration - reboot robot"},
			{49, "Error 49"},
			{50, "Unable to properly detect mopping pad"},
			{51, "Error 51"},
			{52, "Error 52"},
			{53, "Software update required for cleaning head"},
			{54, "RANGE 65"},
			{66, "Memory limit reached - reboot robot"},
			{67, "Error 67"},
			{68, "Camera failed - reboot robot"},
			{69, "RANGE 72"},
			{73, "Pad type changed during cleaning job"},
			{74, "Area limit reached"},
			{75, "Stuck around obstacle"},
			{76, "Internal communication error - reboot robot"},
			{77, "RANGE 87"},
			{88, "Unable to back up"},
			{89, "Mission runtime too long"},
			{90, "RANGE 98"},
			{99, "Unable to localize - move back to home base"},
			{100, "RANGE 1002"},
			{1003, "Internal communication error - reboot robot"},
			{1004, "RANGE 1006"},
			{1007, "Pad actuator hardware failure"},
			{1008, "Pad actuator could not move"},
			{1009, "Pad actuator hardware failure"},
			{1010, "Unable to path back to home base"},
			{1011, "Floor type sensor error"},
			{1012, "Error 1012"},
			{1013, "Tank is leaking"},
			{1014, "Robot fluid level sensor error"},
			{1015, "Tank fluid level sensor error"},
			{1016, "RANGE 9999"}
		};
	}
}