name: CI

on:
  push:
    branches:
      # Only run on branch push, not tag push
      - '**'

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup nuget
      uses: nuget/setup-nuget@v1
      
    - name: Nuget restore
      run: nuget restore HSPI_IRobot.sln
    
    - name: Generate assembly version
      run: |
        $assemblyinfo = Get-Content -Path .\HSPI_IRobot\Properties\AssemblyInfo.cs
        $assemblyversion_line = ($assemblyinfo | Select-String -Pattern "^\[assembly: AssemblyVersion").Line
        $new_version_line = '[assembly: AssemblyVersion("' + $assemblyversion_line.split('"')[1].split('.')[0] + '.' + (Get-Date -UFormat "%y.%V") + '.' + ($env:GITHUB_RUN_NUMBER % 100) + '")]'
        $assemblyinfo.Replace($assemblyversion_line, $new_version_line) | Set-Content -Path .\HSPI_IRobot\Properties\AssemblyInfo.cs -Encoding utf8
      
    - name: MSBuild
      run: |
        msbuild /p:Configuration=Debug HSPI_IRobot.sln
        msbuild /p:Configuration=Release HSPI_IRobot.sln
        
    - name: Stage artifacts
      run: |
        mkdir artifacts
        cp HSPI_IRobot\bin\Release\HSPI_IRobot.exe artifacts\HSPI_IRobot.exe
        cp HSPI_IRobot\bin\Release\*.dll artifacts
        cp HSPI_IRobot.exe.config artifacts\HSPI_IRobot.exe.config
        cp html\*.* artifacts
        cp install.txt artifacts\install.txt
        $release_version = (Get-ChildItem -Filter "artifacts\HSPI_IRobot.exe" | Select-Object -ExpandProperty VersionInfo).FileVersion.Replace('.', '-')
        echo "release_version=$release_version"
        echo "release_version=$release_version" >> $env:GITHUB_ENV
    
    - name: Stage debug artifacts
      run: |
        mkdir artifacts-debug
        cp HSPI_IRobot\bin\Debug\HSPI_IRobot.exe "artifacts-debug\HSPI_IRobot.exe"
        cp HSPI_IRobot\bin\Debug\*.dll artifacts-debug
        cp html\*.* artifacts-debug
        cp HSPI_IRobot.exe.config artifacts-debug\HSPI_IRobot.exe.config
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: iRobot_${{ env.release_version }}
        path: artifacts
    
    - name: Upload debug artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Debug Build
        path: artifacts-debug
